"""Interface para builders de prompt por produto."""
from collections.abc import Callable
from typing import Protocol

PromptFn = Callable[[str], str]


class PromptBuilder(Protocol):
    def build_guardrails(self, salon_name: str) -> str: ...
    def build_receptionist_prompt(self, salon_name: str) -> str: ...
    def build_support_prompt(self, salon_name: str) -> str: ...
    def build_scheduling_prompt(self, salon_name: str) -> str: ...
    def build_lakehouse_prompt(self, salon_name: str) -> str: ...
